FROM jetty:9.4-jre8
FROM <%= image.name_tag %>

USER root
WORKDIR /

<%= snippet('labels', binding) -%>

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

WORKDIR $JETTY_BASE
USER jetty

EXPOSE 8080
ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD ["java","-jar","/usr/local/jetty/start.jar"]
